# Generated by Django 3.2.13 on 2022-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_comments',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글 수'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
    ]
